# Generated by Django 5.0.3 on 2024-04-03 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basemodel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='moviecategory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.basemodel')),
                ('moviecat', models.CharField(max_length=100)),
            ],
            bases=('myapp.basemodel',),
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.basemodel')),
                ('moviename', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=100)),
                ('images', models.CharField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.moviecategory')),
            ],
            bases=('myapp.basemodel',),
        ),
    ]
